sources:
  - name: s1
    database: DEV_DB
    schema: dev_schema
    tables:
      - name: customers
      - name: orders
      - name: payment
      - name: emp
      - name: t_tickets      